#include <pcl/registration/icp_nl.h>
#include <pcl/registration/transforms.h>
#include <pcl/point_representation.h>
#include <pcl/visualization/pcl_visualizer.h>
#include "FilterFunctions.h"
#include "FrameReader.h"
#include "CurvaturePointRepresentation.h"
#include <cpprest\http_client.h>
#include <cpprest\http_listener.h>
#include <cpprest\producerconsumerstream.h>
#include <fstream>
#include <iostream>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/features/normal_3d.h>
#include <boost/thread/thread.hpp>
#include <boost/make_shared.hpp>