#include <pcl/features/normal_3d.h>
#include <pcl/kdtree/kdtree.h>
#include <pcl/octree/octree_pointcloud.h>
#include <pcl/octree/octree_impl.h> 
#include <pcl/sample_consensus/method_types.h>
#include <pcl/sample_consensus/model_types.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/segmentation/extract_clusters.h>
#include <pcl/filters/extract_indices.h>
#include <cpprest\http_client.h>
#include <cpprest\http_listener.h>
#include <cpprest\producerconsumerstream.h>
#include <stdio.h>
#include <fstream>
#include <iostream>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <boost/thread/thread.hpp>
#include <boost/make_shared.hpp>